### PR TITLE
(MODULES-7141) Support Sensitive data type

### PR DESCRIPTION
**Pull request by jpogran**
This is a port of the code in [puppetlabs-dsc PR#324](https://github.com/puppetlabs/puppetlabs-dsc/pull/324) to add Sensitive types to the dsc_lite module.

### CODE REVIEW

**Comment by Iristyle** [comment]
Can be cross-referenced against https://github.com/puppetlabs/puppetlabs-dsc/pull/324/files

Might as well also update the code in https://github.com/puppetlabs/puppetlabs-dsc_lite/blob/master/lib/puppet/provider/base_dsc_lite/powershell.rb#L156-L173

**Comment by jpogran** [comment]
The appveyor failure is due to testing on Puppet v4.2.3. The puppetlabs-dsc and puppetlabs-dsc_lite module differ in what Puppet Gem versions they test.  The dsc_lite module still tests [v4.2.3](https://github.com/puppetlabs/puppetlabs-dsc_lite/blob/master/appveyor.yml#L23), while the dsc module removed it in commit [e1205ef](https://github.com/puppetlabs/puppetlabs-dsc/commit/e1205ef12dcc67b6eab18126f010f4e63b7d3bb3#diff-180360612c6b8c4ed830919bbb4dd459)

**Comment by jpogran** [comment]
Pending https://github.com/puppetlabs/puppetlabs-dsc_lite/pull/50 merge to fix appveyor failure

**Comment by Iristyle** [comment]
#50 merged

**Pull request merged**
