### PR TITLE
Propose small spelling changes

### PR DESCRIPTION
**Pull request by jeis2497052**
do these updates help?

### CODE REVIEW

**Comment by Iristyle** [comment]
Thanks for the contribution @jeis2497052 ... we will get those fixed.

If you feel like updating your PR, the file mode on `spec/unit/puppet/type/base_dsc_spec.rb` was changed from `100644 → 100755`, which is something we typically wouldn't change in a PR. If you can figure out how to fix that and update your commit message to be `(maint) Spec spelling typos`, then we can merge - otherwise, we can handle ourselves in a separate commit.


Thanks!

**Comment by jeis2497052** [comment]
sorry about the file perms change.  I didn't mean to do that???

**Comment by jeis2497052** [comment]
how do the perms look now?

**Comment by lionce** [comment]
Hello @jeis2497052 ,

In order to merge this PR, please resolve the conflicts and rebase it with the latest changes.

Thanks!

**Comment by eimlav** [comment]
Hi @jeis2497052 . Due to a lack of feedback for a number of months I am now closing this PR. Please feel free to re-open should you wish to continue working on it. Thanks!

**Pull request closed without merging**
